sudo: required

language: cpp

services:
 - docker

before_install:
 - docker pull bfarnham/quasar:quasar-open62541
 
script:
 - docker run  --interactive --tty bfarnham/quasar:quasar-open62541 /bin/sh -c "
     echo '********************************************************************' ;
     echo branch $TRAVIS_BRANCH ;
     echo '********************************************************************' ;
     git clone -b $TRAVIS_BRANCH https://github.com/quasar-team/LogIt.git ;
     mkdir LogIt/build && cd build ;
     cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DLOGIT_BUILD_SHARED_LIB=ON -DCMAKE_TOOLCHAIN_FILE=./boost_travis.cmake ;
     make clean && make ;
     exit ;
     "
