list(APPEND LOGIT_SOURCES src/UaTraceSink.cpp)
list(APPEND LOGIT_DEFINITIONS LOGIT_BACKEND_UATRACE)

set(UNIFIED_AUTOMATION_HOME "$ENV{UNIFIED_AUTOMATION_HOME}")
if(NOT UNIFIED_AUTOMATION_HOME)
    message(FATAL_ERROR "LOGIT_BACKEND_UATRACE requires UNIFIED_AUTOMATION_HOME to be set (e.g. /opt/unified-automation with include/ and lib/).")
endif()

set(UNIFIED_AUTOMATION_INCLUDE_DIR "${UNIFIED_AUTOMATION_HOME}/include")
set(UNIFIED_AUTOMATION_LIBRARY_DIR "${UNIFIED_AUTOMATION_HOME}/lib")
if(NOT EXISTS "${UNIFIED_AUTOMATION_INCLUDE_DIR}")
    message(FATAL_ERROR "UNIFIED_AUTOMATION_HOME does not contain include/: ${UNIFIED_AUTOMATION_INCLUDE_DIR}")
endif()
if(NOT EXISTS "${UNIFIED_AUTOMATION_LIBRARY_DIR}")
    message(FATAL_ERROR "UNIFIED_AUTOMATION_HOME does not contain lib/: ${UNIFIED_AUTOMATION_LIBRARY_DIR}")
endif()

find_path(UATRACE_INCLUDE_DIR NAMES uatrace.h
    PATHS "${UNIFIED_AUTOMATION_INCLUDE_DIR}"
    PATH_SUFFIXES "" uabasecpp
    NO_DEFAULT_PATH
)

list(APPEND LOGIT_EXTRA_INCLUDE_DIRS
    "${UNIFIED_AUTOMATION_INCLUDE_DIR}/uastack"
    "${UATRACE_INCLUDE_DIR}"
)

file(GLOB UATRACE_STATIC_LIBS "${UNIFIED_AUTOMATION_LIBRARY_DIR}/*${CMAKE_STATIC_LIBRARY_SUFFIX}")
if(NOT UATRACE_STATIC_LIBS)
    message(FATAL_ERROR "Could not find static libraries in ${UNIFIED_AUTOMATION_LIBRARY_DIR}")
endif()
list(APPEND LOGIT_EXTRA_LINK_LIBS ${UATRACE_STATIC_LIBS})

