list(APPEND LOGIT_SOURCES src/UaTraceSink.cpp)
list(APPEND LOGIT_DEFINITIONS LOGIT_BACKEND_UATRACE)

set(UNIFIED_AUTOMATION_HOME "$ENV{UNIFIED_AUTOMATION_HOME}")
if(NOT UNIFIED_AUTOMATION_HOME)
    message(FATAL_ERROR "LOGIT_BACKEND_UATRACE requires UNIFIED_AUTOMATION_HOME to be set (e.g. /opt/unified-automation with lib/cmake/UASDKCPP/UASDKCPPConfig.cmake).")
endif()

if(NOT EXISTS "${UNIFIED_AUTOMATION_HOME}")
    message(FATAL_ERROR "UNIFIED_AUTOMATION_HOME does not exist: ${UNIFIED_AUTOMATION_HOME}")
endif()

list(APPEND CMAKE_PREFIX_PATH "${UNIFIED_AUTOMATION_HOME}")
find_package(UASDKCPP CONFIG REQUIRED COMPONENTS uabasecpp)

if(NOT TARGET UASDKCPP::uabasecpp)
    message(FATAL_ERROR "UASDKCPP CMake config did not provide UASDKCPP::uabasecpp target.")
endif()

list(APPEND LOGIT_EXTRA_LINK_LIBS UASDKCPP::uabasecpp)
