list(APPEND LOGIT_SOURCES src/UaTraceSink.cpp)
list(APPEND LOGIT_DEFINITIONS LOGIT_BACKEND_UATRACE)

set(UNIFIED_AUTOMATION_HOME "$ENV{UNIFIED_AUTOMATION_HOME}")
set(LIBSSL_HOME "$ENV{LIBSSL_HOME}")
set(LIBXML2_HOME "$ENV{LIBXML2_HOME}")

if(NOT UNIFIED_AUTOMATION_HOME OR NOT LIBSSL_HOME OR NOT LIBXML2_HOME)
    message(FATAL_ERROR "LOGIT_BACKEND_UATRACE requires UNIFIED_AUTOMATION_HOME, LIBSSL_HOME, and LIBXML2_HOME to be set")
endif()

list(PREPEND CMAKE_PREFIX_PATH
    "${UNIFIED_AUTOMATION_HOME}"
    "${LIBSSL_HOME}"
    "${LIBXML2_HOME}"
    )

find_package(OpenSSL CONFIG REQUIRED COMPONENTS SSL Crypto)
find_package(LibXml2 CONFIG REQUIRED)
find_package(UASDKCPP CONFIG REQUIRED COMPONENTS uabasecpp)

if(NOT TARGET UASDKCPP::uabasecpp)
    message(FATAL_ERROR "UASDKCPP CMake config did not provide UASDKCPP::uabasecpp target.")
endif()

list(APPEND LOGIT_EXTRA_LINK_LIBS UASDKCPP::uabasecpp OpenSSL::SSL OpenSSL::Crypto LibXml2::LibXml2)
